### ISSUE TITLE
Dark mode broken under FF 100

### ISSUE THREAD

**Issue by jonschlu** [zvuc/firefox-macos-native-tabbar#1]
The dark mode is broken under FF 100, see photo when window is active:
![IMG](https://user-images.githubusercontent.com/36934298/166522022-b0a69bb0-d794-4190-8cd4-625e8ec1f2d6.jpg)
 
When window is inactive, it looks like this (no transparency):
![IMG 2](https://user-images.githubusercontent.com/36934298/166522178-1b100672-9e46-4163-8952-922b6a873e21.jpg)

**Comment by zvuc** [comment]
Thanks for reporting this. I've updated stylesheet to work again with version 100. 🙏
