### ISSUE TITLE
The windows lag when switching to Mission Control

### ISSUE THREAD

**Issue by YunfangHou** [zvuc/firefox-macos-native-tabbar#10]
See the video below. The playing speed is not adjusted. The windows lag when switching to Mission Control.

I'm not sure if it's because of my device. I'm using MacBook Pro 2019 with Intel Core i5, running macOS Sonoma.

https://github.com/zvuc/firefox-macos-native-tabbar/assets/53991651/b72bcd19-afe8-4f08-9b97-7c190ef84ae8

**Comment by zvuc** [comment]
Misson Control always has been one of the most graphically heavy parts in macOS UI, it lags often when you have a lot of windows open, and adding translucent areas certainly wouldn't help improve the render framerate. From your video it doesn't seem too severe an issue especially considering your machine's age (and it being Intel) — if it bugs you a lot, try removing the translucency altogether then try Mission Control, and see if improves the smoothness. If it does, you'll have to decide if you want to live with it and keep the translucency, or give up for performance.
