### ISSUE TITLE
No css required any more since Firefox 127

### ISSUE THREAD

**Issue by la3rence** [zvuc/firefox-macos-native-tabbar#12]
Thanks for the guidance in this repo. It's really helpful!

Today after I trying to upgrade the latest firefox with the version 127.0.1, I've found a new config to make the browser UI with macOS native tabbar **without setting the css in the profile folder**.

It looks like we can just flip these 2 items to `true` in `about:config` :

- `widget.macos.titlebar-blend-mode.behind-window`
- `browser.theme.macos.native-theme`

Please let me know if it works for you :)

**Comment by zvuc** [comment]
Nice catch there, seems you are right! 
Great news that now there's a much easier way to get the translucent look without having to deal with code.

I'll update the readme to include the tips you mentioned. Thanks!

**Comment by la3rence** [comment]
FYI: A new configuration for the native theme has been added in the latest Firefox Beta version (not quite sure about the specific version, I am now using 133). If the above two properties do not work , please try setting `browser.theme.native-theme` to `true`. It seems that `browser.theme.macos.native-theme` has been deprecated.

**Comment by zvuc** [comment]
@la3rence You're right! I just got updated to version 133 and `browser.theme.native-theme` does do the charm. I will update the readme, thanks much :)
