### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by neondeex** [zvuc/firefox-macos-native-tabbar#2]
![image](https://user-images.githubusercontent.com/30392593/187697634-786f301f-97db-437b-bcbb-2f05b2bab7b6.png)
Did everything in the tutorial.
Enabled render and toolkit
Also as you can see my compositor is already working with transparent effects but
in fire fox is just gray
Im using kde
![image](https://user-images.githubusercontent.com/30392593/187698092-4c9d95ac-75bb-4ca9-ae2e-6ef46fd5e569.png)

**Comment by zvuc** [comment]
Looking at the screenshots it seems that you're on Linux. Sorry to say, but this userstyle will only work on macOS versions of Firefox because the properties giving the translucent render are macOS-specific properties.
