### ISSUE TITLE
Stopped working recently?

### ISSUE THREAD

**Issue by bpwned** [zvuc/firefox-macos-native-tabbar#4]
Thanks again for making this wonderful CSS. it looks like the translucency has disappeared on recent builds, e.g. 20230912211753. Any idea what is happening?

**Comment by zvuc** [comment]
I only track stable releases and on 117.0.1 the translucency is still here (for now). :)
I'll investigate & make changes as needed when the problematic build releases to stable and breaks the stylesheet.

**Comment by zvuc** [comment]
Version 119 rolled out to stable and broke the translucency.
I've fixed it in the latest commit (e914c554e0c3bd3d6bb93e821857c037ecccaf49) and it's working fine again now.

Closing this issue now!
