### ISSUE TITLE
Broken again in Firefox 121

### ISSUE THREAD

**Issue by bdusen** [zvuc/firefox-macos-native-tabbar#7]
Seems to be broken again in Firefox 121. Can anyone confirm?

**Comment by roggmatsz** [comment]
Can confirm, broken on 121 for both Sonoma and Monterey. I hope these issues don't seem like a nuisance; this is by far the best theme I have ever used on FF since the v4 days on Windows 7. Just trying to help it stay alive!

**Comment by zvuc** [comment]
Try applying the latest update I just pushed (10a51e1672a33b23a693624618140a12f675cadf), for now it seems to bring back the translucency.

**Comment by roggmatsz** [comment]
Its works again! Just confirmed.

**Comment by zvuc** [comment]
Thanks for confirming! Closing issue now :)

**Comment by bdusen** [comment]
Thank you! It worked for me too!
